### ISSUE TITLE
Can you provide benchmark information files according to OpenPCDet's data format？

### ISSUE THREAD

**Issue by jlqzzz** [SmartBot-PJLab/MV-JAR#1]
Dear author,

Thank you very much for your great work!

Will you provide implementation code based on the OpenPCDet framework? 

Can you provide benchmark information files according to OpenPCDet's data format？

**Comment by RunsenXu** [comment]
Dear jlqzzz,

Thank you for your interest in our work!

We currently do not have plans to provide an implementation based on the OpenPCDet framework. 

As for the benchmark, we have released the original Waymo filenames for our benchmark sequences, which should help you adapt the data to different codebases, including OpenPCDet. You can use these filenames to convert the original Waymo data into OpenPCDet's data format or any other format that suits your needs. You can refer to the updated README.md. 

We hope this helps, and please feel free to reach out if you have any further questions.

Best regards,
Runsen
