### ISSUE TITLE
Confuse about the model

### ISSUE THREAD

**Issue by hht1996ok** [SmartBot-PJLab/MV-JAR#2]
@RunsenXu  Thank you for your great work! As far as I know, the current mainstream backbone will include downsampling operations. Have you ever thought about how to adapt these models?

**Comment by RunsenXu** [comment]
Hi @hht1996ok .

Thank you for your interest in our work! You raise a valid point regarding the downsampling operations in some architectures.

To adapt such models, you can consider using an upsampling module, such as deconvolution (deconv), to generate feature maps at the original scale. By doing so, you can maintain the spatial resolution while still leveraging the capabilities of the backbone architecture. Additionally, when fine-tuning your model, you can only transfer the backbone weights.

I hope this helps! If you have any further questions or suggestions, please feel free to ask.

**Comment by hht1996ok** [comment]
That's a good idea, thanks for your reply!
